### ISSUE TITLE
Inquiry about some versions

### ISSUE THREAD

**Issue by y2sman** [AIM3-RUC/MPMQA#2]
Thanks for your brilliant work.

I’m trying to follow your work, but there are some troubles while installing environments.

Can you specify the exact torch version and apex version?

**Comment by zhangliang-04** [comment]
Hi @y2sman,
This repo could run with `python=3.7.13`, `CUDA=11.3` and `torch=1.10.1+cu113`. For apex, I remember that I encountered an error for the latest version and solved it by checking the git repo of apex to a specific version before installing. You can try this version: `3ff1a10f72ec07067c4e44759442329804ac5162`.

**Comment by y2sman** [comment]
It works perfectly when installed with the official installation code of the specified apex version that you offered(3ff1a10f72ec07067c4e44759442329804ac5162).
```
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```
I appreciate your prompt reply.
Additionally, I describe my setup procedure for the researchers who are going to reproduce this work.

1. create docker-container
```
python==3.7.13
pip==20.0.2
```
with `conda install -y pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge
`

2. install detectron2
```
git checkout be792b959bca9a
python -m pip install -e detectron2
```

3. install apex
```
git checkout 3ff1a10f72ec07067c4e44759442329804ac5162
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

4. install detector
```
python setup.py build develop
```

5. install Java
```
sudo apt-get update
sudo apt-get install openjdk-8-jdk
```

6. install python packages
```
deepspeed==0.6.0
fitz==0.0.1.dev2
jsonlines==3.0.0
numpy==1.21.5
omegaconf==2.1.1
opencv_python==4.5.5.62
Pillow==9.2.0
pycocoevalcap==1.2
PyMuPDF==1.19.6
pyparsing==3.0.7
scikit_learn==1.0.2
setuptools==58.0.4
transformers==4.17.0
```

7. install nlg-eval
```
pip install git+https://github.com/Maluuba/nlg-eval.git@2.2.0
```

Thanks again!
